# Generated by Django 2.2.7 on 2019-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='briefinform',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
