# Generated by Django 2.2.7 on 2019-12-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0003_userprofile_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiless'},
        ),
    ]
