# Generated by Django 2.2.7 on 2019-12-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0005_auto_20191212_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goroskop.Sex'),
        ),
    ]
