# Generated by Django 2.2.7 on 2019-12-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0007_auto_20191212_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goroskop.Zodiac'),
        ),
    ]
