# Generated by Django 2.2.7 on 2019-12-12 20:27

from django.db import migrations, models
import goroskop.models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0010_auto_20191212_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnersex', models.CharField(blank=True, max_length=7, null=True, verbose_name=goroskop.models.Sex)),
            ],
        ),
    ]
