# Generated by Django 2.2.7 on 2019-12-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0011_compability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compability',
            new_name='Compability_u',
        ),
    ]
