# Generated by Django 2.2.7 on 2019-12-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0012_auto_20191212_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compability_u',
            new_name='Compability',
        ),
    ]
