# Generated by Django 2.2.7 on 2019-12-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0013_auto_20191212_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='compability',
            name='zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goroskop.Zodiac'),
        ),
    ]
