# Generated by Django 2.2.7 on 2019-12-13 13:36

from django.db import migrations, models
import goroskop.models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0014_compability_zodiac'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='URL'),
        ),
        migrations.AlterField(
            model_name='compability',
            name='partnersex',
            field=models.CharField(default='male', max_length=7, verbose_name=goroskop.models.Sex),
        ),
    ]
