# Generated by Django 2.2.7 on 2019-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0015_auto_20191213_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
