# Generated by Django 2.2.7 on 2019-12-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0017_auto_20191213_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiless'},
        ),
    ]
