# Generated by Django 2.2.7 on 2019-12-14 11:17

from django.db import migrations, models
import django.db.models.deletion
import goroskop.models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0020_compability_pzodiac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnersex', models.CharField(default='male', max_length=7, verbose_name=goroskop.models.Sex)),
                ('pzodiac', models.CharField(default='Gemini', max_length=40)),
                ('zodiac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goroskop.Zodiac')),
            ],
        ),
        migrations.DeleteModel(
            name='Compability',
        ),
    ]
