# Generated by Django 2.2.7 on 2019-12-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0027_auto_20191214_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='briefinform',
            new_name='hobby',
        ),
    ]
